services:
  redis:
    image: redis:8.8-m03-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  postgres:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_PASSWORD=front
      - POSTGRES_USER=front
      - POSTGRES_DB=front
    volumes:
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U front -d front" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrator-front:
    build:
      context: .
      dockerfile: Alembic.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  front:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - migrator-front
      - redis
      - postgres
    ports:
      - "8181:8080"
