services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  postgres:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_PASSWORD=front
      - POSTGRES_USER=front
      - POSTGRES_DB=front
    volumes:
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
  migrator-front:
    build:
      context: .
      dockerfile: Alembic.Dockerfile
    depends_on:
      - postgres
      - redis

  migrator-back:
    image: migrator-back:latest

  back:
    image: teleback:latest
    depends_on:
      - migrator-back
      - redis
      - postgres

  front:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - migrator-front
      - redis
      - postgres
      - back
    ports:
      - "8080:8080"


